### ISSUE TITLE
consider using Lombok

### ISSUE THREAD

**Issue by XenoAmess** [cyanpotion/cyan_potion#53]
still considering.
might apply it at next big reconstruction.

**Comment by Taxerap** [comment]
Yup, Java programmers are always looking for ways to be lazier.

**Comment by XenoAmess** [comment]
> Yup, Java programmers are always looking for ways to be lazier.

delete Java and the statement is still correct😄

**Comment by XenoAmess** [comment]
Consider over.
Using lombok.
