### ISSUE TITLE
Should not use Texture for picture directly,and should add a new class Picture instead

### ISSUE THREAD

**Issue by XenoAmess** [cyanpotion/cyan_potion#8]
as title

**Comment by Taxerap** [comment]
What exactly do you mean by "picture"? If you mean you want to distinguish 2D tiles and 3D textures, you should just go ahead and make children classes for them. The word "Picture" is somehow confusing.

By the way, as you are using Lwjgl, it's better to use the stb digital format loader instead of writing your own. Of course, if you want to just experience then I wouldn't put a word on that (I tried to do so and had some very funny results 23333).

**Comment by XenoAmess** [comment]
> What exactly do you mean by "picture"? If you mean you want to distinguish 2D tiles and 3D textures, you should just go ahead and make children classes for them. The word "Picture" is somehow confusing.
> 
> By the way, as you are using Lwjgl, it's better to use the stb digital format loader instead of writing your own. Of course, if you want to just experience then I wouldn't put a word on that (I tried to do so and had some very funny results 23333).

Sorry for my poor english here.
1. In the current version when we draw something we use Texture directly.
But, Texture  is just the raw picture, and as we want to describe and hold a transformed version of texture, like flatten,or monochrome，or twisting，or mirror，we need to create a new layer named Picture.
For example, now in rpg module, each Unit hold a Texture. But it actually shall hold a Picture,but not a raw texture data.

2. I'm actually not formiliar with lwjgl and I just use it as a tool, but have not learned it yet.
If you can link some demo about how to use "stb digital format loader" here, I will be very appreciated.
Thank you.

**Comment by Taxerap** [comment]
https://github.com/State-of-War-PostBar/SOW-Remastered/blob/3af9c0c87dac2778d33c0ace0a717a5d0eb17f16/src/main/java/cn/stateofwar/sowr/graphic/render/Texture2D.java

Here is a stupid version of textures, focus on the last past, I presented the way to load texture from file path and resource.
Also you can find documents of STB from https://github.com/nothings/stb

**Comment by XenoAmess** [comment]
> https://github.com/State-of-War-PostBar/SOW-Remastered/blob/3af9c0c87dac2778d33c0ace0a717a5d0eb17f16/src/main/java/cn/stateofwar/sowr/graphic/render/Texture2D.java
> 
> Here is a stupid version of textures, focus on the last past, I presented the way to load texture from file path and resource.
> Also you can find documents of STB from https://github.com/nothings/stb

Thx. 
I'm focused on fixing codes smell now.
I will consider it when I finish the fixing.
